### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by reinos** [Johanbos/home-assistant-import#134]
Hi there,

Is there also a MacOS version of the tool?

Please let me know.

**Comment by Johanbos** [comment]
Pfff https://unix.stackexchange.com/questions/13711/differences-between-sed-on-mac-osx-and-other-standard-sed.

**Comment by Johanbos** [comment]
@reinos please check out release https://github.com/Johanbos/home-assistant-import/releases/tag/v0.2.1-ci.184. The Darwin compressed file should be installable/runnable on a MacOS! I have no mac machine to test with.
