### ISSUE TITLE
Home assistant add-on

### ISSUE THREAD

**Issue by brjhaverkamp** [Johanbos/home-assistant-import#145]
As you write at the end of your own README, it would be very nice/cool to have this included in home assistant as an add-on.
It would make the migration of data much smoother and streamlined.
Please consider making this app and add-on.

Kind regards,

Bert

**Comment by Johanbos** [comment]
I have reconsidered and for now I have no intention to do this. Learning phyton would be fun, but an import is a one time job making the add-in less valuable. The audience is also so small (I think).
