### ISSUE TITLE
today negative after import history

### ISSUE THREAD

**Issue by decommentator** [Johanbos/home-assistant-import#151]
Imported the history with removing all current data in HA. Direct after import everything looks ok.
After some time today is all negative as if HA thinks I'm delevering instead of using.
(Did the same yesterday with the same result)

Using domoticz 2023.2

**Comment by Johanbos** [comment]
It could be that the incorrect sensorid was used during import. In my HA there are different sensors for consumption and production of electricity.

![_20230728_065130](https://github.com/Johanbos/home-assistant-import/assets/6775602/8d068db2-48f1-42dc-847d-338c7d1a63f3)

Investigating on sql level would be the best option to find out which sensor is doing what job.

**Comment by decommentator** [comment]
the sensor is correct. Today everything is ok. History is ok. Except yesterday the time from import
![Schermafbeelding 2023-07-28 100522](https://github.com/Johanbos/home-assistant-import/assets/71527824/be4ef5ce-5995-45e2-9656-0e314d05c0d4)
same for gaz. Only wrong @importtime

**Comment by Johanbos** [comment]
Ah next hint: use the value divider/multiplier. You might need to go from Wh to KWh etc.

**Comment by decommentator** [comment]
it's strange as "today" is not in domoticz export
tried it with the different divider/multiplier options

**Comment by Erwin033** [comment]
At first, a big thank you for making this tool!
As decommentator, I have the same problem. 

Would it be possible to delete al today's data?

**Comment by Johanbos** [comment]
It is very easy to skip/delete parts of the import sql script. Leave out the last insert into value line. It should be at the end of all the values, recognizable by the date.

Within HA, if you know Sql well enough, you can alter any weird value manually. Be careful ofcourse and make sure you have your backup.

**Comment by Johanbos** [comment]
Ah, in that case.. Yes, I should add the option to set an end date. I understand now that the incorrect sum could cause these issues.

As soon as have added this, I'll update this issue.

**Comment by Johanbos** [comment]
Could you give https://github.com/Johanbos/home-assistant-import/releases/tag/v0.2.1-ci.140 a try?

It incudes the end date option and I also tried to improve the options page, including a better description about the 'sum' / relative existing data.

**Comment by Johanbos** [comment]
Oops, I tested it with a pv export. I will test with domoticz soon.

**Comment by Johanbos** [comment]
Hmm, my Domoticz DB (from 2022, it's a bit old) is still working without any errors. Is there a error message you can share?

**Comment by Johanbos** [comment]
I've created #174 for the application crash issues. Multi people are experiencing them.

**Comment by Johanbos** [comment]
@enduring78 Please try https://github.com/Johanbos/home-assistant-import/releases/tag/v0.2.1-ci.151 with a specific end date.

**Comment by Johanbos** [comment]
Updated end date parsing and description in https://github.com/Johanbos/home-assistant-import/releases/tag/v0.2.1-ci.159
