### ISSUE TITLE
Idea: Description for exporting correct database from Domoticz

### ISSUE THREAD

**Issue by TheRed-E** [Johanbos/home-assistant-import#168]
Im was trying to export the correct data from Domoticz, to start fumbeling around with the data and see how it works.
I couldn't find the correct export function on the dashboard... eventualy found it, but maybe it is an idea to expand the readme files with some extra instruction on getting the data from the Domoticz database? or a link to a good description?

**Comment by Johanbos** [comment]
Great idea. Do you still have a screenshot of the domoticz menu? I no longer have it running.

**Comment by TheRed-E** [comment]
I can make one, but currently I have not a correct export. Application crashes when importing the *.db file.

**Comment by Johanbos** [comment]
Oh no, follow #174 for the application crash.

**Comment by Johanbos** [comment]
https://github.com/Johanbos/home-assistant-import/releases/tag/v0.2.1-ci.154 is available.

Added links to export manuals.
![265221742-f074ae5d-7148-4d9a-8201-c97a219ca197](https://github.com/Johanbos/home-assistant-import/assets/6775602/6ebaec13-d226-4eda-addb-11eb512c63b4)

[https://www.domoticz.com/wiki/Application_Settings#Backup_.2F_Restore_Database">domoticz.com/wiki/Application_Settings#Backup_.2F_Restore_Database](https://www.domoticz.com/wiki/Application_Settings#Backup_.2F_Restore_Database%22%3Edomoticz.com/wiki/Application_Settings#Backup_.2F_Restore_Database)
https://manuals.sma.de/SI-12/en-US/3877479691.html
