### ISSUE TITLE
Tool inserts DATES as where HA expects TIMESTAMP

### ISSUE THREAD

**Issue by michaelblaas** [Johanbos/home-assistant-import#94]
Hi,
I'm trying to migrate my energydata from Domoticz to HA but I cannot get results so far.

As far as I can see the import tool inserts records like this:

_insert into statistics (created, start, state, sum, metadata_id) values
("2017-01-27 02:00:00.000000", "2017-01-27 02:00:00.000000", 1170.917, 0.000, 103)_

But if I do a select on the HA-table all records have a NULL value for created and start and have the created_ts and start_ts fields filled instead:

_id | created | start | mean | min | max | last_reset | state | sum | metadata_id | created_ts | start_ts | last_reset_ts
520 | NULL | NULL | NULL | NULL | NULL | NULL | 12372.731 | 0.0 | 103 | 1675954810.380533 | 1675951200.0 | NULL_

Could you explain what is happening or if HA is supposed to convert te dates into timestamps somehow?

Thanks
Michael

**Comment by Johanbos** [comment]
Oh noes. HA has had an [update ](https://github.com/home-assistant/core/commit/abf0c87e40743cd2c0b1014805b084e6834792de) where fields have been deprecated. So this tool no longer functions correctly since [2023.3.3](https://github.com/home-assistant/core/releases/tag/2023.3.3)... :-(

**Comment by michaelblaas** [comment]
Thanks for the answer. Based on this info I was able to do some conversion of the insert and update statements in XLS and finally got the history uploaded...

**Comment by Johanbos** [comment]
I will try to convert the `datetime` values to `timestamps` with [Date.parse()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse) functionality. This saves others some time.

**Comment by freijn** [comment]
Tried to import, but unfortunately not any record visible in HA. 

if possible please fix it again as this was on my Wishlist for a long time....

Many thanks for putting your time in this!

Home Assistant 2023.3.4
Supervisor 2023.03.1
Operating System 9.5
Frontend-versie: 20230309.0 - latest

**Comment by freijn** [comment]
> 
> If anyone is interested I'm willing to share my XLS.
Very much interested !!!!!  Would you be so kind to share the XLS ?

 Thanks

   Frank

**Comment by michaelblaas** [comment]
Hi @freijn and all,

I'll tidy up the XLS, add some documentation as how to use it and post it here (hopefully later today).

**Comment by freijn** [comment]
Found it..  A2 is the past cell  :-)

**Comment by michaelblaas** [comment]
Sorry for that @freijn, contents must be pasted into cell A2 (as you found out yourself ;-)). I'll change the instructions and repost the XLS.

**Comment by freijn** [comment]
Michael, no sorry for that, happy you sharing a solve !
Please see my other comment as well.  Would be nice if you put
 that in the xls as well?

btw. I still didn't manage to get the data imported....  :-(

**Comment by fvaneeken** [comment]
I managed to import the data from my PV-installation, today.

This is the SQL scipt I used:
```
update statistics set sum = sum + 10609970.000 where metadata_id = 16 and start_ts > unixepoch("2023-03-16 02:00:00.000000")

update statistics_short_term set sum = sum + 10609970.000 where metadata_id = 16 and start_ts > unixepoch("2023-03-16 02:00:00.000000")

insert into statistics (created_ts, start_ts, state, sum, metadata_id) values
(unixepoch("2022-12-01 02:00:00.000000"), unixepoch("2022-12-01 02:00:00.000000"), 10248200.000, 10237970.000, 16),
(unixepoch("2022-12-02 02:00:00.000000"), unixepoch("2022-12-02 02:00:00.000000"), 10248500.000, 10238270.000, 16),
(unixepoch("2022-12-03 02:00:00.000000"), unixepoch("2022-12-03 02:00:00.000000"), 10248800.000, 10238570.000, 16),
(unixepoch("2022-12-04 02:00:00.000000"), unixepoch("2022-12-04 02:00:00.000000"), 10248900.000, 10238670.000, 16)
```

You have to use the unixepoch() function in SQLite and change the fields **start** to **start_ts** and **created** to **created_ts.**

**Comment by michaelblaas** [comment]
Hi @freijn,

Send me a DM and we can see if we can schedule a remote assistance session (in Dutch :-)). Btw: I assume you've double checked the entity ID's in HA? And have you tried using the scripts as mentioned above as alternative to my XLS?

**Comment by Johanbos** [comment]
@freijn I have incorporated the solution of @fvaneeken into a new version of the tool https://github.com/Johanbos/home-assistant-import/releases/tag/v0.2.1-ci.169. Could you try again?

Don't forget to backup your HA ;-)

**Comment by freijn** [comment]
Hi Johan

It does generate an error message : 

UNIQUE constraint failed: statistics.metadata_id, statistics.start_ts

**Comment by fvaneeken** [comment]
Hello Frank Reijn,

This is caused by a double record in the last insert statement. Look for
two lines with the same date. Delete one of these lines and try again to
insert the other records again.

Best regards,
Frank

Op za 18 mrt. 2023 om 09:57 schreef Frank Reijn ***@***.***>

**Comment by freijn** [comment]
Frank @fvaneeken  or Michael @michaelblaas   online now ?   ( and willing to have a look in my system? )

**Comment by freijn** [comment]
Sorry for spamming you. I have found doulbe records 3 times now..      making progress  ppffff 

Thanks for the support !!!!  :-)

**Comment by freijn** [comment]
![Capture](https://user-images.githubusercontent.com/45577312/226108595-63f92cba-1de8-424d-9cfd-b1f46adcf5eb.JPG)
Sooooooo happy now :-)     Thanks Guys !!

Special thanks to Johan !!

**Comment by Johanbos** [comment]
There is an option to Validate, Skip or add erroneous data. But I see now it doesn't handle duplicates well. I've created https://github.com/Johanbos/home-assistant-import/issues/99 to fix this.
![image](https://user-images.githubusercontent.com/6775602/226112613-582947b1-7c32-44f0-bbf8-b105e21773cf.png)

**Comment by fvaneeken** [comment]
I'm glad you figured out what caused the problem.

Op za 18 mrt. 2023 14:17 schreef Frank Reijn ***@***.***>:
